version: '3.3'

services:
  travle-diary-mysql-server-project:
    image: travle-diary-mysql-server-project
    container_name: travle-diary-mysql-server-project
    command: mysqld
    restart: always
    # volumes:
    #   - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    ports:
      - '33306:3306'
    expose:
      - '33306'
