version: '3.3'

services:
  travle-diary-mysql-server-project:
    image: mysql
    container_name: travle-diary-mysql-server-project
    ports:
      - '20022:22'
      - '20080:80'
      - '28080:8080'
    expose:
      - '20022'
      - '20080'
      - '28080'
